name: Gradle verify

on:
  workflow_call:
    secrets:
      gradle-encryption-key:
        required: true

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v4

      - name: Java setup
        id: java-setup
        uses: actions/setup-java@v4
        with:
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Gradle setup
        id: gradle-setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.gradle-encryption-key }}

      - name: Gradle ktlint check
        id: gradle-ktlint-check
        run: ./gradlew ktlintCheck

      - name: Gradle test
        id: gradle-test
        run: ./gradlew test

      - name: Gradle build
        id: gradle-build
        run: ./gradlew build
