name: Gradle build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      gpg-signing-key:
        required: true
      gpg-signing-key-id:
        required: true
      gpg-signing-key-password:
        required: true
      gradle-encryption-key:
        required: true
      maven-central-username:
        required: true
      maven-central-password:
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v5

      - name: Java setup
        id: java-setup
        uses: actions/setup-java@v5
        with:
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Gradle setup
        id: gradle-setup
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.gradle-encryption-key }}

      - name: Gradle publish
        id: gradle-publish
        run: ./gradlew -Pversion=${{ inputs.version }} publishAndReleaseToMavenCentral --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.maven-central-username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.maven-central-password }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.gpg-signing-key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.gpg-signing-key-id }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.gpg-signing-key-password }}
