name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  gradle-verify:
    name: Gradle verify
    uses: ./.github/workflows/gradle-verify.yml
    secrets:
      gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
