name: Release

on:
  release:
    types:
      - published

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  gradle-publish:
    name: Gradle publish
    uses: ./.github/workflows/gradle-publish.yml
    secrets:
      gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      gpg-signing-key: ${{ secrets.GPG_SIGNING_KEY }}
      gpg-signing-key-id: ${{ secrets.GPG_SIGNING_KEY_ID }}
      gpg-signing-password: ${{ secrets.GPG_SIGNING_PASSWORD }}
      maven-central-username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
    with:
      version: ${{ github.event.release.tag_name }}
