name: Release

on:
  release:
    types:
      - published

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  gradle-publish:
    name: Gradle publish
    uses: ./.github/workflows/gradle-publish.yml
    secrets:
      gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      gpg-signing-key: ${{ secrets.GPG_SIGNING_KEY }}
      gpg-signing-passphrase: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
    with:
      version: ${{ github.event.release.tag_name }}
